backend:
  name: github
  repo: lwind233/lwind233.github.io
  branch: source

media_folder: source/images
public_folder: /images

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} - {{date}} - {{body}}"
    sortable_fields: ["title", "date", "author"]
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
